version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    expose:
      - "9411"

  api-gateway:
#    image: microservices-tracing/api-gateway:latest
    container_name: microservices-tracing-api-gateway
    build: ./api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin


  customer-service:
#    image: microservices-tracing/customer-service:latest
    container_name: microservices-tracing-customer-service
    build: ./customer-service
    ports:
      - "8081:8081"
    expose:
      - "8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - api-gateway

  credit-report-service:
 #   image: microservices-tracing/credit-report-service:latest
    container_name: microservices-tracing-credit-report-service
    build: ./credit-report-service
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - api-gateway
